### ISSUE TITLE
Issue in Nimble dialog component

### ISSUE THREAD

**Issue by rajeshswain424** [Nimble-Institute/nimble-design-system#118]
we need the fontsize and fontweight for top and button action button.

**Comment by Manoj201** [comment]
@rajeshswain424 @sharath7178 
This issue was fixed v2.2.3 onwards

for the dialog component added new 2 props
<img width="901" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/4e11e8f1-5eac-4d9d-84d5-357be369e7a3">


for top action, we are using Nimble Biutton props
for Nimble Button, i have added below new prop 
<img width="890" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/9c6c7823-efd0-44fd-8f19-739590a34e35">

so in the dialog, we can pass font-weight like this for buttons
<img width="237" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/b815e7cf-f23e-4e28-a6f5-169298da72ea">

for button font sizes we have to discuss this because if we add the font size prop to the button it will affect to size prop (small, medium, and large ). For now, we will close this issue. for button font size we will discuss it with @NimbleMax and create a new issue.
