### ISSUE TITLE
want to change header font family in Nimble dailog

### ISSUE THREAD

**Issue by sharath7178** [Nimble-Institute/nimble-design-system#140]
![image](https://github.com/Nimble-Institute/nimble-design-system/assets/83495605/c84f9a38-508b-4b19-8714-cb1ec5c94293)

**Comment by Manoj201** [comment]
@sharath7178 This issue is closing because this feature has already there

<img width="1036" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/7ca4385c-5eea-49a6-a100-ba586b89f83a">

If it's not working please update the library. If there any questions please send me a message

**Comment by sharath7178** [comment]
here i want to gave different font family for header and footer(cancel and save button) so add one prop for header font family

**Comment by Manoj201** [comment]
added the new PROP
<img width="902" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/90871a4f-ac80-4780-bdea-4858b8533927">
