### ISSUE TITLE
Nimble Tab - tab widths must fit to text content

### ISSUE THREAD

**Issue by rasaralaya-nimble-expert** [Nimble-Institute/nimble-design-system#158]
![current nimbletab behavior](https://github.com/Nimble-Institute/nimble-design-system/assets/145844108/30a98a88-024b-4f9b-a4d8-802a70cd9865)

- **currently**, 
    - the nimble tab component's tabs have a fixed width

![nimbletab component must have tabs that fit to the contents of the title text](https://github.com/Nimble-Institute/nimble-design-system/assets/145844108/50fd624b-ad03-469b-9ec9-3edef0dc5f0e)

- **what is required** 
    - is the tabs should automatically adjust their width to fit the content as shown in the above screenshot
    - if this changes everywhere this component is used, it might break things, so it might be better to make the tabs fit to content an optional prop

- ** NMT-143 ** requires this change

**Comment by Manoj201** [comment]
This issue was fixed. workaround for developer
@rasaralaya-nimble-expert please add props variant= 'standard' and adjust the tab width based on your requirement using width prop.

<img width="794" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/31fc5f19-f3bc-4abf-9899-5757beecd753">
