### ISSUE TITLE
Extra space in autocomplete and select

### ISSUE THREAD

**Issue by NimbleMax** [Nimble-Institute/nimble-design-system#70]
<img width="929" alt="Schermafbeelding 2023-08-04 om 13 12 47" src="https://github.com/Nimble-Institute/nimble-design-system/assets/74488289/6d45fece-c0f9-4019-bed7-360661a16bab">

**Comment by NimbleMax** [comment]
It's not solved

**Comment by Manoj201** [comment]
This issue was fixed and tested 
<img width="591" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/4f5c3562-f251-49e0-8e59-1743ed1503fe">


<img width="565" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/3e8545f3-d4ad-4ead-85df-3583f87b2934">

<img width="579" alt="image" src="https://github.com/Nimble-Institute/nimble-design-system/assets/5594092/8df94211-4dcf-4107-9d40-3a3315298524">
